// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.27.1
// source: internal/testdata/helloword/v1/helloword.proto

package v1

import (
	_ "github.com/go-fox/fox/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SayHiRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Header string `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Name   string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *SayHiRequest) Reset() {
	*x = SayHiRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_testdata_helloword_v1_helloword_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SayHiRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SayHiRequest) ProtoMessage() {}

func (x *SayHiRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_testdata_helloword_v1_helloword_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SayHiRequest.ProtoReflect.Descriptor instead.
func (*SayHiRequest) Descriptor() ([]byte, []int) {
	return file_internal_testdata_helloword_v1_helloword_proto_rawDescGZIP(), []int{0}
}

func (x *SayHiRequest) GetHeader() string {
	if x != nil {
		return x.Header
	}
	return ""
}

func (x *SayHiRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type SayHiResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Content string `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
}

func (x *SayHiResponse) Reset() {
	*x = SayHiResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_testdata_helloword_v1_helloword_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SayHiResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SayHiResponse) ProtoMessage() {}

func (x *SayHiResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_testdata_helloword_v1_helloword_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SayHiResponse.ProtoReflect.Descriptor instead.
func (*SayHiResponse) Descriptor() ([]byte, []int) {
	return file_internal_testdata_helloword_v1_helloword_proto_rawDescGZIP(), []int{1}
}

func (x *SayHiResponse) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

var File_internal_testdata_helloword_v1_helloword_proto protoreflect.FileDescriptor

var file_internal_testdata_helloword_v1_helloword_proto_rawDesc = []byte{
	0x0a, 0x2e, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x74, 0x65, 0x73, 0x74, 0x64,
	0x61, 0x74, 0x61, 0x2f, 0x68, 0x65, 0x6c, 0x6c, 0x6f, 0x77, 0x6f, 0x72, 0x64, 0x2f, 0x76, 0x31,
	0x2f, 0x68, 0x65, 0x6c, 0x6c, 0x6f, 0x77, 0x6f, 0x72, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x0d, 0x68, 0x65, 0x6c, 0x6c, 0x6f, 0x77, 0x6f, 0x72, 0x6c, 0x64, 0x2e, 0x76, 0x31, 0x1a,
	0x19, 0x66, 0x6f, 0x78, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x54, 0x0a, 0x0c, 0x53, 0x61,
	0x79, 0x48, 0x69, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x24, 0x0a, 0x06, 0x68, 0x65,
	0x61, 0x64, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x42, 0x0c, 0x82, 0x9a, 0x21, 0x08,
	0x0a, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x52, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72,
	0x12, 0x1e, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x42, 0x0a,
	0x82, 0x9a, 0x21, 0x06, 0x12, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x22, 0x29, 0x0a, 0x0d, 0x53, 0x61, 0x79, 0x48, 0x69, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x32, 0x9c, 0x01, 0x0a, 0x0e,
	0x47, 0x72, 0x65, 0x65, 0x74, 0x65, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x70,
	0x0a, 0x05, 0x53, 0x61, 0x79, 0x48, 0x69, 0x12, 0x1b, 0x2e, 0x68, 0x65, 0x6c, 0x6c, 0x6f, 0x77,
	0x6f, 0x72, 0x6c, 0x64, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x61, 0x79, 0x48, 0x69, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x1c, 0x2e, 0x68, 0x65, 0x6c, 0x6c, 0x6f, 0x77, 0x6f, 0x72, 0x6c,
	0x64, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x61, 0x79, 0x48, 0x69, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x2c, 0xc2, 0xdb, 0x20, 0x28, 0x0a, 0x02, 0x61, 0x61, 0x0a, 0x03, 0x62, 0x62,
	0x62, 0x22, 0x1d, 0x22, 0x1b, 0x2f, 0x76, 0x31, 0x2f, 0x68, 0x65, 0x6c, 0x6c, 0x77, 0x6f, 0x72,
	0x64, 0x2f, 0x67, 0x72, 0x65, 0x65, 0x74, 0x65, 0x72, 0x2f, 0x73, 0x61, 0x79, 0x5f, 0x68, 0x69,
	0x1a, 0x18, 0x82, 0x9d, 0x20, 0x14, 0xc2, 0xed, 0x1a, 0x08, 0x55, 0x73, 0x65, 0x72, 0x41, 0x75,
	0x74, 0x68, 0xc2, 0xed, 0x1a, 0x04, 0x54, 0x65, 0x73, 0x74, 0x42, 0x39, 0x5a, 0x37, 0x67, 0x69,
	0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x67, 0x6f, 0x2d, 0x66, 0x6f, 0x78, 0x2f,
	0x66, 0x6f, 0x78, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x74, 0x65, 0x73,
	0x74, 0x64, 0x61, 0x74, 0x61, 0x2f, 0x68, 0x65, 0x6c, 0x6c, 0x6f, 0x77, 0x6f, 0x72, 0x64, 0x2f,
	0x76, 0x31, 0x3b, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_internal_testdata_helloword_v1_helloword_proto_rawDescOnce sync.Once
	file_internal_testdata_helloword_v1_helloword_proto_rawDescData = file_internal_testdata_helloword_v1_helloword_proto_rawDesc
)

func file_internal_testdata_helloword_v1_helloword_proto_rawDescGZIP() []byte {
	file_internal_testdata_helloword_v1_helloword_proto_rawDescOnce.Do(func() {
		file_internal_testdata_helloword_v1_helloword_proto_rawDescData = protoimpl.X.CompressGZIP(file_internal_testdata_helloword_v1_helloword_proto_rawDescData)
	})
	return file_internal_testdata_helloword_v1_helloword_proto_rawDescData
}

var file_internal_testdata_helloword_v1_helloword_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_internal_testdata_helloword_v1_helloword_proto_goTypes = []any{
	(*SayHiRequest)(nil),  // 0: helloworld.v1.SayHiRequest
	(*SayHiResponse)(nil), // 1: helloworld.v1.SayHiResponse
}
var file_internal_testdata_helloword_v1_helloword_proto_depIdxs = []int32{
	0, // 0: helloworld.v1.GreeterService.SayHi:input_type -> helloworld.v1.SayHiRequest
	1, // 1: helloworld.v1.GreeterService.SayHi:output_type -> helloworld.v1.SayHiResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_internal_testdata_helloword_v1_helloword_proto_init() }
func file_internal_testdata_helloword_v1_helloword_proto_init() {
	if File_internal_testdata_helloword_v1_helloword_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_internal_testdata_helloword_v1_helloword_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*SayHiRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_testdata_helloword_v1_helloword_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*SayHiResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_internal_testdata_helloword_v1_helloword_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_testdata_helloword_v1_helloword_proto_goTypes,
		DependencyIndexes: file_internal_testdata_helloword_v1_helloword_proto_depIdxs,
		MessageInfos:      file_internal_testdata_helloword_v1_helloword_proto_msgTypes,
	}.Build()
	File_internal_testdata_helloword_v1_helloword_proto = out.File
	file_internal_testdata_helloword_v1_helloword_proto_rawDesc = nil
	file_internal_testdata_helloword_v1_helloword_proto_goTypes = nil
	file_internal_testdata_helloword_v1_helloword_proto_depIdxs = nil
}
